### PR TITLE
Dark mode fixes

### LINKED ISSUE #228: make icon color for passkey list component adaptable
**Background**
Currently the passkey icon on the very left and the delete icon on the very right are always is black. Currently, it's almost not visible for users

**TODO**
 - [x] Can we introduce two color modes for these icons as well: One for light and another one for dark mode
 - [x] The general passkey icon + delete icon should be then in white or black (depending on the mode).
 - [x] Also for individual AAGUIDs, there are icons for light and dark mode, see here: https://github.com/passkeydeveloper/passkey-authenticator-aaguids/blob/main/aaguid.json. Can we please also use the right icons for light and dark (if you need help on downloading the files properly, please contact @vincentdelitz)

### LINKED ISSUE #266: Proper dark mode support in react application
## Issue
We should have a proper way for react component to preserve it's dark mode status

**Expected behavior**
Correct icons should be selected based on the dark mode state.

### PR DESCRIPTION
**Pull request by Aby-JS**

### CODE REVIEW

File: packages/react/src/contexts/ThemeProvider.tsx [hunk 1]
```diff
@@ -7,11 +8,12 @@ import ThemeContext from './ThemeContext';
 interface ThemeProviderProps extends PropsWithChildren {
   theme?: string | CustomThemes;
   darkMode?: 'on' | 'off' | 'auto';
```
Comment (incorbador) [inline packages/react/src/contexts/ThemeProvider.tsx]: we now have darkModeSubject and darkMode, why do we need both?

**Review by incorbador — APPROVED** [review]
